FROM ubuntu:latest

# MAINTAINER instruction is deprecated
LABEL maintainers="Austreelis <dev@austreelis.net>"

RUN apt update
RUN apt install -y bind9-dnsutils iputils-ping telnet curl mutt

CMD ["tail", "-f", "/dev/null"]
